title: Angela Ayd Photography
email: angelaaydphotography@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Angela Ayd Photography Portrait Engagement Graduation Maternity Pregnancy Children Family Photographs
baseurl: "/angelaaydphotography" # the subpath of your site, e.g. /blog
url: "https://adamayd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adam_ayd
github_username: adamayd

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
# markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - README.md
